### ISSUE TITLE
Fix velocity object reference

### ISSUE THREAD

**Issue by Briuor** [Nicholas-03/canvas-game#1]
On function **spawnParticles()** line 37:
```js
    const velocity = {
        x: 0,
        y: 0
    };

    for (let i = 0; i < 2; i++) {
        x = Math.random() * canvas.width;
        y = Math.random() * canvas.height;
        particles.push(new Particle(x, y, radius, color, velocity));
    }
```
The problem is the velocity object, object in javascript is always passed by reference, so you are assigning the same velocity reference to the two particles.
When you change the velocity of a particle you are changing the same velocity reference.
You can create the velocity object inline like below:
Try the code:
```js
for (let i = 0; i < 2; i++) {
        x = Math.random() * canvas.width;
        y = Math.random() * canvas.height;
        particles.push(new Particle(x, y, radius, color, { x: 0, y: 0 }));
    }
```

**Comment by Nicholas-03** [comment]
Now it works, thanks a lot!
